[versions]

[libraries]

# build dependencies
build-agp = "com.android.tools.build:gradle:7.0.4"
build-binarycompat = "org.jetbrains.kotlinx:binary-compatibility-validator:0.8.0"
build-dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.6.0"
build-download = "de.undercouch:gradle-download-task:4.1.2"
build-hilt = "com.google.dagger:hilt-android-gradle-plugin:2.40.5"
build-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
build-kover = "org.jetbrains.kotlinx:kover:0.4.4"
build-mavenpublish = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
build-okhttp = "com.squareup.okhttp3:okhttp:4.9.3"
build-semver = "com.vdurmont:semver4j:3.1.0"
build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.0.5"
build-dependencyanalysis = "com.autonomousapps:dependency-analysis-gradle-plugin:0.79.0"

[bundles]