[versions]
compose = "1.1.1"
apollo = "3.1.0"
kotlin = "1.6.10"
coroutines = "1.6.0"
dagger = "2.41"

[libraries]
# build dependencies
build-agp = "com.android.tools.build:gradle:7.1.2"
build-binarycompat = "org.jetbrains.kotlinx:binary-compatibility-validator:0.8.0"
build-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
build-download = "de.undercouch:gradle-download-task:5.0.2"
build-apollo-graphql = { module = "com.apollographql.apollo3:apollo-gradle-plugin", version.ref = "apollo" }
build-hilt = "com.google.dagger:hilt-android-gradle-plugin:2.41"
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-kover = "org.jetbrains.kotlinx:kover:0.4.4"
build-mavenpublish = "com.vanniktech:gradle-maven-publish-plugin:0.19.0"
build-okhttp = "com.squareup.okhttp3:okhttp:4.9.3"
build-semver = "com.vdurmont:semver4j:3.1.0"
build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.3.0"
build-dependencyanalysis = "com.autonomousapps:dependency-analysis-gradle-plugin:0.80.0"

accompanist-insets = "com.google.accompanist:accompanist-insets:0.23.1"
accompanist-systemui = "com.google.accompanist:accompanist-systemuicontroller:0.23.1"

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-datastore-prefs-core = "androidx.datastore:datastore-preferences-core:1.0.0"
androidx-lifecycle-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.1"

apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-cache-memory = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo"}
apollo-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo"}

compose-activity = "androidx.activity:activity-compose:1.4.0"
compose-compiler = "androidx.compose.compiler:compiler:1.1.1"
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material3 = "androidx.compose.material3:material3:1.0.0-alpha06"
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

material = "com.google.android.material:material:1.5.0"

coil-kt-compose = "io.coil-kt:coil-compose:1.4.0"
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

thirdparty-kotlin-result = "com.michael-bull.kotlin-result:kotlin-result:1.1.14"

testing-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
testing-junit = "junit:junit:4.13.2"
testing-junit-ext = "androidx.test.ext:junit:1.1.3"
testing-junit-ui = "androidx.compose.ui:ui-test-junit4:1.1.1"
testing-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
testing-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
testing-kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
