[versions]
compose = "1.1.0-rc01"
apollo = "3.0.0"
kotlin = "1.6.0"
[libraries]

# build dependencies
build-agp = "com.android.tools.build:gradle:7.1.0"
build-binarycompat = "org.jetbrains.kotlinx:binary-compatibility-validator:0.8.0"
build-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
build-download = "de.undercouch:gradle-download-task:4.1.2"
build-apollo-graphql = { module = "com.apollographql.apollo3:apollo-gradle-plugin", version.ref = "apollo" }
build-hilt = "com.google.dagger:hilt-android-gradle-plugin:2.40.5"
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-kover = "org.jetbrains.kotlinx:kover:0.4.4"
build-mavenpublish = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
build-okhttp = "com.squareup.okhttp3:okhttp:4.9.3"
build-semver = "com.vdurmont:semver4j:3.1.0"
build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.2.0"
build-dependencyanalysis = "com.autonomousapps:dependency-analysis-gradle-plugin:0.79.0"

androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-lifecycle-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0"

compose-activity = "androidx.activity:activity-compose:1.4.0"
compose-compiler = "androidx.compose.compiler:compiler:1.1.0-rc02"
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
apollo-cache-memory = { module = "com.apollographql.apollo3:apollo-normalized-cache", version.ref = "apollo"}
apollo-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite", version.ref = "apollo"}

material = "com.google.android.material:material:1.5.0"

testing-junit = "junit:junit:4.13.2"
testing-junit-ext = "androidx.test.ext:junit:1.1.3"
testing-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
testing-junit-ui = "androidx.compose.ui:ui-test-junit4:1.1.0-rc01"

[bundles]