package dev.skrilltrax.baka.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1760a5)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd3e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001c3a)
val md_theme_light_secondary = Color(0xFF005ac3)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd6e2ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001a43)
val md_theme_light_tertiary = Color(0xFFbd0046)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdadf)
val md_theme_light_onTertiaryContainer = Color(0xFF400012)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFe6e0ec)
val md_theme_light_onSurfaceVariant = Color(0xFF48454f)
val md_theme_light_outline = Color(0xFF79767f)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)
val md_theme_light_inversePrimary = Color(0xFFa1c9ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFa1c9ff)
val md_theme_dark_onPrimary = Color(0xFF00315e)
val md_theme_dark_primaryContainer = Color(0xFF004884)
val md_theme_dark_onPrimaryContainer = Color(0xFFd3e4ff)
val md_theme_dark_secondary = Color(0xFFabc7ff)
val md_theme_dark_onSecondary = Color(0xFF002e6b)
val md_theme_dark_secondaryContainer = Color(0xFF004395)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e2ff)
val md_theme_dark_tertiary = Color(0xFFffb2be)
val md_theme_dark_onTertiary = Color(0xFF670022)
val md_theme_dark_tertiaryContainer = Color(0xFF910033)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdadf)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF48454f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc9c4cf)
val md_theme_dark_outline = Color(0xFF938f99)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)
val md_theme_dark_inversePrimary = Color(0xFF1760a5)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
